# Generated by Django 3.2.20 on 2023-08-09 07:19

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=150, validators=[users.validators.validate_password], verbose_name='password'),
        ),
    ]
