# Generated by Django 3.2.20 on 2023-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_date',
            field=models.DateTimeField(auto_now=True, verbose_name='otp_date_expired'),
        ),
    ]
